### ISSUE TITLE
Favicon removed remain as a ghost

### ISSUE THREAD

**Issue by BoscoCarvalho** [archetyped/favicon-rotator#4]
Dear friend,
after uploading two icons, I decided to remove them.
Now, when I refresh the site to see them alternating, I get some 'empty' instances.
How can I correct this?
The site is http://editoranaves.com.br/
Thank you in advance for your kind support.

**Comment by archetyped** [comment]
Hi, when no icons are explicitly defined, web browsers use the `favicon.ico` file in your site's root directory.  You can remove this file if you do not want browsers to use this icon as a fallback.
