### ISSUE TITLE
Apple touch icon

### ISSUE THREAD

**Issue by hollisterca** [archetyped/favicon-rotator#7]
With your plugin installed, should this work?
https://www.teawea.com/apple-touch-icon-120×120.png
https://www.teawea.com/apple-touch-icon-precomposed.png
https://www.teawea.com/apple-touch-icon.png

You mention in your Highlights:
New: Set icon for Touch devices (Android, iPhone, iPad, iPod Touch, etc.)

I get an error 404

Otherwise, how does it work?

thanks

**Comment by archetyped** [comment]
Hi, have you set the desired image in the **Touch Icon** section of Favicon Rotator's settings?  If so, please provide a link to a page where the icon is not being added to the page's source, and I would be glad to take a look.

**Comment by hollisterca** [comment]
Currently I am not using your plugin, I used https://realfavicongenerator.net/ to create the icons and uploaded them. I guess the 120x120 is an old style. Well, I am just wondering, do I have to setup each apple icon or is that something your plugin does?
the head section on my site has the settings from the above URL.
Will your plugin provide all that ?

**Comment by archetyped** [comment]
Favicon Rotator allows you to set the icon to be displayed as the touch icon on supported devices.  Multiple image files are not required.
