### ISSUE TITLE
Favicon not changing from default one

### ISSUE THREAD

**Issue by scorp1984** [archetyped/favicon-rotator#9]
I have the issue of the icon not showing on the browser tabs:

https://www.responseability.co/

Version 1.2.10

Other Plugins:
Akismet Anti-spam: Spam Protection
Contact Form 7
LiteSpeed Cache
Sassy Social Share
Sender.net email marketing

Chrome, Brave, Firefox Latest versions

**Comment by archetyped** [comment]
Hi, the favicon set by Favicon Rotator is not displayed at the link you provided because additional favicons are set further down in the page's source.  Removing these other favicon declarations will allow the browser to use the icon set by Favicon Rotator.
